### ISSUE TITLE
bcmath requirement and a misspelling

### ISSUE THREAD

**Issue by chrisgraham** [mishal/iless#40]
The linked patch removes the need for bcmath, via simple fallback code.

It also fixes the misspelling of 'subtract'.

https://gist.github.com/chrisgraham/791bfb84d7d04e4cdb1d

**Comment by mishal** [comment]
Thanks for looking at it! Can you create a pull request? And unit test for this?

**Comment by chrisgraham** [comment]
I've made 3 pull requests for you. I know I haven't broken any of your test passing, and I fixed one of the tests. However if run without bcmath, the tests massively fail, which is to be expected given the precision is off. I don't think there's a solution to that, bcmath is recommended for someone needing that precision, and you're going to run your tests with bcmath on.
