### ISSUE TITLE
Is there any test for 'no changes' to compilation?

### ISSUE THREAD

**Issue by dleffler** [mishal/iless#49]
Based on the docs/examples, we'd ALWAYS have to get the css and then write it out, but that's not the best use of a cache...e.g., if we're running the compiler for every less sheet on our page and then have to write out every css file on each page load, that's a lot of time wasted.  

In both lessphp & less.php the cachedCompile() method returns a compiled date so you can determine if the cache/output was updated.  I don't see anything like that being set or availble with the $parser->cache.

**Comment by mishal** [comment]
There is no direct method, but using the public API you can accomplish the functionality you need. I've created an example in the `example` directory. 

Does it cover what you need?

**Comment by dleffler** [comment]
Thanks, that works for me!
