### ISSUE TITLE
Doesn't properly parse variables within an @import if not at begnning of string

### ISSUE THREAD

**Issue by dleffler** [mishal/iless#50]
Though the following will import/compile correctly (since the variable is at the beginning of the string
```
@import "@{swatch}/variables.less";
```
this will not, because it doesn't parse out the variable (@swatch is the name of the bootswatch)
```
@import "../../../bootstrap3/less/@{swatch}/variables.less";
```

**Comment by mishal** [comment]
I've added test for this issue, and it passes. 

Can you pls provide a failing test case?

**Comment by dleffler** [comment]
I have a pretty complicated integration, but the only difference I can see for the failed import (no error, just doesn't pick up the swatch styles) is that I set the variable (to compile bootstrap3) via $compiler->setVariables()...it appears my other compilations event with the 1st example above are not correctly importing the 'swatch'.  A similar compilation I use in a 'wrapped' bootstrap3 with the 'swatch' variable set in the wrapper .less file (as your test does) works (see below).

```
.exp-skin {
	@swatch: "cerulean"; // newui uses this swatch
	@themepath: "cerulean"; // hack to prevent crash

	@import "bootstrap.less";
}
```

**Comment by mishal** [comment]
Can you please provide minimal failing test case for this? I'm not able to reproduce this.

**Comment by dleffler** [comment]
A better test (#50) would be
```
$parser->setVariables(array('swatch'=>'foobar;');
$parser->parseString('@import "../../../bootstrap3/less/@{swatch}/variables.less";');
```
instead of
```
$parser->parseString('@swatch: foobar;@import "../../../bootstrap3/less/@{swatch}/variables.less";')
```
which fails for me, and accurately reflects what my code is doing

**Comment by dleffler** [comment]
It looks as if the variables are only passed to the rule parser if they are a part of the string/file (ruleset) being passed and NOT any variables (customVariables?) set by method call.  Maybe around the ILess_Parser_Core->to CSS() method during the precompilation visitors call.
