### ISSUE TITLE
Issue #50 has resurfaced - Doesn't properly parse variables within an @import

### ISSUE THREAD

**Issue by dleffler** [mishal/iless#53]
See #50 which seems to have lost the fix in the upgrade to iLess v2.x??  This time simply moving 
```
$this->prepareVariables($this->context, $variables);
```
 before  
```
foreach ($this->getPreCompileVisitors() as $visitor) {
```
doesn't seem to correct it.

**Comment by mishal** [comment]
I did not put the test back to the 2.0 branch when merging. Will be fixed soon. 

Sorry
