### ISSUE TITLE
Parser->toCSS() crashes on empty variable?

### ISSUE THREAD

**Issue by dleffler** [mishal/iless#56]
When attempting to compile and passing an empty variable (@swatch: "") the compiler will hard crash with no error message (Core.php line #447) during Parser->toCss().  @swatch is used to determine the folder name for the 'swatch' which empty would indicate the one in the root folder.  This works correctly under iLess v1.7.0.

**Comment by mishal** [comment]
Can you provide some less code for this issue? I've created a test for this - The empty variable is properly propagating.. 

Thanks!

**Comment by dleffler** [comment]
Seems to have been fixed with the issue #55 fix..unable to reproduce locally any more.

**Comment by mishal** [comment]
Closed in 4e34714
