### ISSUE TITLE
parser fails with error code for long data uri

### ISSUE THREAD

**Issue by bstoney** [mishal/iless#61]
Using URLs with very long data uri i.e. for an embedded font-face, causes php to exit with an error code during parsing:
for example:

`
@font-face {
  font-family: 'Glyphicons Halflings';
  src:url(data:font/opentype;base64,n04AAEFNAA...<snip 26,000 characters>...gKA9IEaYJg);
}
`

A PHPUnit test will abort with the message:

`Process finished with exit code -1073741571 (0xC00000FD)`

This might also be the cause of #38

**Comment by mishal** [comment]
Could you pls create PR for this fix?
